### ISSUE TITLE
Pagination of legend panel is broken in version 2.1.0

### ISSUE THREAD

**Issue by avispeng** [zingchart/zingchart-react#20]
I forked and modified the zingchart-react example code:
https://codesandbox.io/s/zingchart-react-wrapper-example-oj5db?file=/src/App.js
If you go to page 2 on legend panel, it's blank.
This works fine with version 2.0.1.
Hope this can be fixed. Thanks.

**Comment by damntrecky** [comment]
Hi there,

This is actually a library issue and not a react wrapper issue. This bug has been fixed in the library in v2.8.9. We will look into fixing this in the wrapper.

![Screen Recording 2020-04-23 at 02 03 PM](https://user-images.githubusercontent.com/38665452/80149365-658dad00-856b-11ea-90ae-12908d08d030.gif)

**Comment by avispeng** [comment]
Thank you!
