### ISSUE TITLE
Not Working in IE 11

### ISSUE THREAD

**Issue by nehaappsbee** [zingchart/zingchart-react#26]
I have implemented in my react project, and it is working fine in all browsers except IE. Can u help me out to make it work in react project.

**Comment by damntrecky** [comment]
The breakdown is we are using a packer tool (http://dean.edwards.name/packer/) to encode our JavaScript to make it much smaller. IE 11 has some issue with that which makes it VERY hard to debug since this is only an encoded syntax error. Since all the code is a string this makes debugging even harder. 

The short term solution. We are debating shipping the unpacked version for es6 library output. This would alleviate the issue but also add 120 kb in size.

The long term solution would be to fix the error and determine and stable solution for all browsers. We are also discussing internally the benefits of compression vs packing with/without gzip. Since we encode the library, natural web gzip compression is less efficient since the algorithm looks for similar patterns. With the packed version already being encoded there aren't many similar patterns so gzip compression doesn't work as well. If we gzip the unpacked version of the library we are very similar in size to the gzip version of the packed library.

**Comment by dev-sareno** [comment]
I may probably be mistaken by your issue, but I have this working on my IE11-specific project. I used Polyfills configuration to compile the create-react-app (TypeScript) to be IE11-compatible from these instructions:
- [https://create-react-app.dev/docs/supported-browsers-features/](https://create-react-app.dev/docs/supported-browsers-features/)
- [https://github.com/facebook/create-react-app/blob/main/packages/react-app-polyfill/README.md](https://github.com/facebook/create-react-app/blob/main/packages/react-app-polyfill/README.md)

**Comment by jeanettephung** [comment]
Unfortunately, there are no longer any plans to support IE11.
If you are currently a paying customer, we would be open for discussion about this matter.
However, check out the [ZingChart library](https://github.com/zingchart/zingchart), which should support IE11.
